# Generated by Django 3.0.3 on 2020-09-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fun_functions', '0002_trianglearea_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaximumEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('first_side', models.IntegerField()),
                ('second_side', models.IntegerField()),
                ('calculated_side', models.IntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepeatingFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('string_to_repeat', models.CharField(max_length=200)),
                ('repeat_n_times', models.IntegerField()),
                ('repeated_string', models.CharField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondsConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('time_type', models.CharField(choices=[('Hours', 'Hours'), ('Minutes', 'Minutes')], max_length=200)),
                ('amount', models.IntegerField()),
                ('seconds', models.IntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
